### ISSUE TITLE
Kibana 6.8.2 - Plugin Installs but doesn't show up.

### ISSUE THREAD

**Issue by hackdefendr** [nabilbendafi/country-flag-fieldformatters#3]
Simply put...there is no Country Flag option under index patterns.

Kibana starts up fine though, which is a challenge with this and newer versions.

**Comment by nabilbendafi** [comment]
Version bumped (to **1.2.2**). You should now be able to install it on _Kibana_ version **6.8.2**
Simply run command
```bash
kibana-plugin install https://github.com/nabilbendafi/country-flag-fieldformatters/releases/download/v1.2.2/country-flag-fieldformatters-1.2.2.zip
```

```bash
bash-4.2$ kibana --version
6.8.2

bash-4.2$ /usr/share/kibana/bin/kibana-plugin list
country-flag-fieldformatters@1.2.2
```

Sadly, it doesn't seem to be possible to have a plugin version that matches **all** _Kibana_ versions (or at least same minor version). So even if plugin code is untouched, I need to bump version number in _package.json_
Otherwise you get message like:
`Plugin installation was unsuccessful due to error "Plugin country-flag-fieldformatters [6.6.0] is incompatible with Kibana [6.8.2]"`

**Comment by nabilbendafi** [comment]
@hackdefendr I guess that I can close this issue, now ?

**Comment by hackdefendr** [comment]
Yup.  Everything is good now.

**Comment by nabilbendafi** [comment]
Cool. Thx.
